from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.asm import assemble, parse_source
from scripts.check_asm_corpus import validate_manifest
from tb.coverage_utils import coverage_from_program, final_state_dict


def load_manifest(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as fh:
        return json.load(fh)


def render_markdown(manifest: dict, manifest_path: Path) -> str:
    failures = validate_manifest(manifest, manifest_path)
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise ValueError(f"assembler manifest is invalid:\n{joined}")

    lines = [
        "<!-- Generated by scripts/asm_corpus_report.py. Do not edit by hand. -->",
        "",
        "# Assembler Regression Corpus",
        "",
        "This page is generated from `docs/assembler-regressions.json` and checked by the Python-model CI lane.",
        "",
        "| Program | Source | Hex bytes | Final state | Coverage signature |",
        "|---|---|---|---|---|",
    ]

    for entry in manifest["programs"]:
        source = entry["source"]
        source_path = PROJECT_ROOT / source
        stmts, labels = parse_source(source_path.read_text(encoding="utf-8"))
        mem = assemble(stmts, labels)
        observed_hex = [f"{value:02X}" for value in mem]
        final_state = final_state_dict(mem, max_cycles=256)
        coverage = coverage_from_program(mem, max_cycles=256)

        expected_hex = entry["expected_hex"]
        if observed_hex != expected_hex:
            raise ValueError(f"{entry['name']}: generated hex does not match manifest")

        final = (
            f"ACC={final_state['acc']} PC={final_state['pc']} "
            f"Z={final_state['zero']} C={final_state['carry']} "
            f"N={final_state['neg']} V={final_state['overflow']} H={final_state['halted']}"
        )
        coverage_text = (
            f"bitmap `{coverage['opcode_hit_bitmap']}`, "
            f"cycles={coverage['total_cycles']}, "
            f"illegal={coverage['illegal_opcode_hit']}, "
            f"jz_taken={coverage['jz_taken']}, "
            f"jz_not_taken={coverage['jz_not_taken']}"
        )
        hex_text = "`" + " ".join(expected_hex) + "`"
        lines.append(f"| `{entry['name']}` | `{source}` | {hex_text} | {final} | {coverage_text} |")

    lines.extend(
        [
            "",
            "Regenerate this page after intentional corpus edits with:",
            "",
            "```powershell",
            ".\\scripts\\generate-asm-corpus-docs.ps1",
            "```",
            "",
            "```bash",
            "bash scripts/generate-asm-corpus-docs.sh",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and check assembler corpus documentation.")
    parser.add_argument("--manifest", type=Path, default=Path("docs/assembler-regressions.json"))
    parser.add_argument("--output", type=Path, default=Path("docs/assembler-regressions.md"))
    parser.add_argument("--check", action="store_true", help="Fail if the generated output is stale.")
    args = parser.parse_args()

    manifest_path = (PROJECT_ROOT / args.manifest).resolve()
    output_path = (PROJECT_ROOT / args.output).resolve()
    expected = render_markdown(load_manifest(manifest_path), manifest_path)

    if args.check:
        if not output_path.exists():
            print(f"Assembler corpus doc is missing: {output_path}", file=sys.stderr)
            raise SystemExit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"Assembler corpus doc is stale: {output_path}. "
                "Regenerate with scripts/generate-asm-corpus-docs.*",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"Assembler corpus doc is up to date: {args.output}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
