from __future__ import annotations

import argparse
import re
import sys
from collections import Counter
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.run_mutation_campaign import BENCHES, MUTATIONS, apply_mutation


def md_escape(value: object) -> str:
    return str(value).replace("|", r"\|")


def validate_mutation_definitions() -> list[str]:
    failures: list[str] = []
    benches_by_name = {bench.name: bench for bench in BENCHES}

    bench_name_counts = Counter(bench.name for bench in BENCHES)
    for bench_name, count in sorted(bench_name_counts.items()):
        if count != 1:
            failures.append(f"bench '{bench_name}' appears {count} times")

    for bench in BENCHES:
        if not bench.binary_name:
            failures.append(f"bench '{bench.name}' has an empty binary_name")
        for source in bench.sources:
            if not (PROJECT_ROOT / source).exists():
                failures.append(f"bench '{bench.name}' references missing source '{source}'")

    mutation_name_counts = Counter(mutation.name for mutation in MUTATIONS)
    for mutation_name, count in sorted(mutation_name_counts.items()):
        if count != 1:
            failures.append(f"mutation '{mutation_name}' appears {count} times")

    for mutation in MUTATIONS:
        prefix = f"mutation '{mutation.name}'"
        if not re.fullmatch(r"[a-z0-9_]+", mutation.name):
            failures.append(f"{prefix} must use lowercase snake_case")
        if not mutation.category:
            failures.append(f"{prefix} has an empty category")
        if not mutation.description:
            failures.append(f"{prefix} has an empty description")
        if not mutation.bench_names:
            failures.append(f"{prefix} has no bench scope")
        if not mutation.replacements:
            failures.append(f"{prefix} has no replacements")

        target_path = PROJECT_ROOT / mutation.target_file
        if not target_path.exists():
            failures.append(f"{prefix} references missing target '{mutation.target_file}'")
            continue

        for bench_name in mutation.bench_names:
            bench = benches_by_name.get(bench_name)
            if bench is None:
                failures.append(f"{prefix} references unknown bench '{bench_name}'")
                continue
            if mutation.target_file not in bench.sources:
                failures.append(f"{prefix} target '{mutation.target_file}' is not compiled by bench '{bench_name}'")

        for index, (old, new) in enumerate(mutation.replacements):
            if not old:
                failures.append(f"{prefix} replacement {index} has an empty old snippet")
            if old == new:
                failures.append(f"{prefix} replacement {index} does not change the snippet")

        try:
            base_text = target_path.read_text(encoding="utf-8")
            mutated_text = apply_mutation(base_text, mutation)
        except ValueError as exc:
            failures.append(f"{prefix} cannot be applied: {exc}")
            continue

        if mutated_text == base_text:
            failures.append(f"{prefix} did not change '{mutation.target_file}'")

    return failures


def render_markdown() -> str:
    failures = validate_mutation_definitions()
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise ValueError(f"mutation definitions are invalid:\n{joined}")

    mutations_by_bench = {
        bench.name: [mutation.name for mutation in MUTATIONS if bench.name in mutation.bench_names]
        for bench in BENCHES
    }
    category_counts = Counter(mutation.category for mutation in MUTATIONS)

    lines = [
        "<!-- Generated by scripts/mutation_catalog.py. Do not edit by hand. -->",
        "",
        "# Mutation Catalog",
        "",
        "This page is generated from `scripts/run_mutation_campaign.py` and checked by the Python-model CI lane.",
        "",
        "## Summary",
        "",
        f"- Total mutations: {len(MUTATIONS)}",
        f"- Total benches: {len(BENCHES)}",
        "- Categories: "
        + ", ".join(f"`{category}`={count}" for category, count in sorted(category_counts.items())),
        "",
        "## Bench Scope",
        "",
        "| Bench | Sources | Scoped mutations |",
        "|---|---|---|",
    ]

    for bench in sorted(BENCHES, key=lambda item: item.name):
        sources = "<br>".join(f"`{source}`" for source in bench.sources)
        scoped = ", ".join(f"`{name}`" for name in sorted(mutations_by_bench[bench.name])) or "none"
        lines.append(f"| `{bench.name}` | {sources} | {scoped} |")

    lines.extend(
        [
            "",
            "## Mutations",
            "",
            "| Mutation | Category | Target | Bench scope | Replacement count | Description |",
            "|---|---|---|---|---|---|",
        ]
    )

    for mutation in sorted(MUTATIONS, key=lambda item: item.name):
        benches = ", ".join(f"`{name}`" for name in mutation.bench_names)
        lines.append(
            "| `{name}` | `{category}` | `{target}` | {benches} | {count} | {description} |".format(
                name=mutation.name,
                category=mutation.category,
                target=mutation.target_file,
                benches=benches,
                count=len(mutation.replacements),
                description=md_escape(mutation.description),
            )
        )

    lines.extend(
        [
            "",
            "Regenerate this page after intentional mutation edits with:",
            "",
            "```powershell",
            ".\\scripts\\generate-mutation-catalog.ps1",
            "```",
            "",
            "```bash",
            "bash scripts/generate-mutation-catalog.sh",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and check the mutation catalog documentation.")
    parser.add_argument("--output", type=Path, default=Path("docs/mutation-catalog.md"))
    parser.add_argument("--check", action="store_true", help="Fail if the generated output is stale.")
    args = parser.parse_args()

    output_path = (PROJECT_ROOT / args.output).resolve()
    expected = render_markdown()

    if args.check:
        if not output_path.exists():
            print(f"Mutation catalog is missing: {output_path}", file=sys.stderr)
            raise SystemExit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"Mutation catalog is stale: {output_path}. "
                "Regenerate with scripts/generate-mutation-catalog.*",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"Mutation catalog is up to date: {args.output}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
