from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.register_map import PROTOCOLS
from tb.cpu_lib import ReferenceCPU, disassemble_program
from tb.protocol_conformance import build_protocol_conformance_scenarios


@dataclass(frozen=True)
class ScenarioSummary:
    name: str
    program_len: int
    max_cycles: int
    verify_loaded_program: bool
    halted: int
    acc: int
    pc: int
    flags: str
    first_instructions: tuple[str, ...]


PROTOCOL_TESTS = {
    "direct-core": "tb/test_simple_cpu.py",
    "mmio": "tb/test_simple_cpu_mmio.py",
    "apb": "tb/test_simple_cpu_apb.py",
    "wishbone": "tb/test_simple_cpu_wishbone.py",
    "axi-lite": "tb/test_simple_cpu_axi_lite.py",
}


def scenario_summaries() -> tuple[ScenarioSummary, ...]:
    summaries: list[ScenarioSummary] = []
    for scenario in build_protocol_conformance_scenarios():
        model = ReferenceCPU()
        model.load_program(scenario.program)
        model.run(max_cycles=scenario.max_cycles)
        summaries.append(
            ScenarioSummary(
                name=scenario.name,
                program_len=len(scenario.program),
                max_cycles=scenario.max_cycles,
                verify_loaded_program=scenario.verify_loaded_program,
                halted=model.halted,
                acc=model.acc,
                pc=model.pc,
                flags=f"Z{model.zero} C{model.carry} N{model.neg} V{model.overflow}",
                first_instructions=tuple(disassemble_program(scenario.program)[:4]),
            )
        )
    return tuple(summaries)


def validate_protocol_catalog() -> list[str]:
    failures: list[str] = []
    scenarios = scenario_summaries()
    names = [scenario.name for scenario in scenarios]

    if len(names) != len(set(names)):
        failures.append("protocol conformance scenarios contain duplicate names")
    if {"smoke", "logic_ops", "jump_loop", "branch_stress", "random_dataflow"} - set(names):
        failures.append("protocol conformance scenario set is missing an expected tutorial scenario")

    for scenario in scenarios:
        if scenario.program_len > 16:
            failures.append(f"{scenario.name}: program length exceeds 16-byte instruction memory")
        if not scenario.halted:
            failures.append(f"{scenario.name}: reference model did not halt within {scenario.max_cycles} cycles")

    for protocol, test_path in PROTOCOL_TESTS.items():
        path = PROJECT_ROOT / test_path
        if not path.exists():
            failures.append(f"{protocol}: missing conformance test file `{test_path}`")
            continue
        text = path.read_text(encoding="utf-8")
        if "run_protocol_conformance_suite" not in text:
            failures.append(f"{protocol}: `{test_path}` does not call run_protocol_conformance_suite")

    protocol_names = {view.name for view in PROTOCOLS}
    for expected in ("MMIO", "APB", "Wishbone", "AXI-Lite"):
        if expected not in protocol_names:
            failures.append(f"register-map protocol views missing `{expected}`")

    readme_text = (PROJECT_ROOT / "README.md").read_text(encoding="utf-8")
    plan_text = (PROJECT_ROOT / "docs" / "verification-plan.md").read_text(encoding="utf-8")
    if "docs/protocol-conformance.md" not in readme_text:
        failures.append("README.md must link to docs/protocol-conformance.md")
    if "docs/protocol-conformance.md" not in plan_text:
        failures.append("docs/verification-plan.md must link to docs/protocol-conformance.md")

    return failures


def render_markdown() -> str:
    failures = validate_protocol_catalog()
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise ValueError(f"protocol conformance catalog is invalid:\n{joined}")

    scenarios = scenario_summaries()
    lines = [
        "<!-- Generated by scripts/protocol_catalog.py. Do not edit by hand. -->",
        "",
        "# Protocol Conformance Catalog",
        "",
        "This page is generated from `tb/protocol_conformance.py` and checked by the Python-model CI lane.",
        "",
        "## Summary",
        "",
        f"- Shared scenarios: {len(scenarios)}",
        f"- Protocol test files: {len(PROTOCOL_TESTS)}",
        "- Every listed test file must call `run_protocol_conformance_suite`.",
        "- Scenario final states are computed with the same `ReferenceCPU` scoreboard used by the tests.",
        "",
        "## Scenarios",
        "",
        "| Scenario | Program bytes | Max cycles | Verify load | Final ACC | Final PC | Flags | First instructions |",
        "|---|---:|---:|---|---:|---:|---|---|",
    ]

    for scenario in scenarios:
        lines.append(
            "| `{name}` | {program_len} | {max_cycles} | `{verify}` | 0x{acc:02X} | 0x{pc:X} | `{flags}` | {insns} |".format(
                name=scenario.name,
                program_len=scenario.program_len,
                max_cycles=scenario.max_cycles,
                verify=scenario.verify_loaded_program,
                acc=scenario.acc,
                pc=scenario.pc,
                flags=scenario.flags,
                insns="<br>".join(f"`{insn}`" for insn in scenario.first_instructions),
            )
        )

    lines.extend(["", "## Protocol Test Coverage", "", "| Adapter | Test file | Contract |", "|---|---|---|"])
    for adapter, test_path in PROTOCOL_TESTS.items():
        lines.append(
            f"| `{adapter}` | `{test_path}` | reset, load, optional readback, run, halt wait, sample, `ReferenceCPU` comparison |"
        )

    lines.extend(
        [
            "",
            "Regenerate this page after intentional conformance-scenario edits with:",
            "",
            "```powershell",
            ".\\scripts\\generate-protocol-catalog.ps1",
            "```",
            "",
            "```bash",
            "bash scripts/generate-protocol-catalog.sh",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and check the protocol conformance scenario catalog.")
    parser.add_argument("--output", type=Path, default=Path("docs/protocol-conformance.md"))
    parser.add_argument("--check", action="store_true", help="Fail if the generated output is stale.")
    args = parser.parse_args()

    output_path = (PROJECT_ROOT / args.output).resolve()
    expected = render_markdown()

    if args.check:
        if not output_path.exists():
            print(f"Protocol conformance catalog is missing: {output_path}", file=sys.stderr)
            raise SystemExit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"Protocol conformance catalog is stale: {output_path}. "
                "Regenerate with scripts/generate-protocol-catalog.*",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"Protocol conformance catalog is up to date: {args.output}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
