from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


@dataclass(frozen=True)
class RegisterEntry:
    name: str
    address: str
    access: str
    producer: str
    description: str


@dataclass(frozen=True)
class ProtocolView:
    name: str
    rtl: str
    bus_helper: str
    address_signal: str
    notes: str


REGISTERS: tuple[RegisterEntry, ...] = (
    RegisterEntry("SHADOW_IMEM", "0x00-0x0F", "RW", "shadow_imem", "Program shadow image bytes."),
    RegisterEntry("STATUS", "0x10", "R", "dbg flags", "Bits `[4:0]` are `HALTED`, `OVERFLOW`, `NEG`, `CARRY`, `ZERO`."),
    RegisterEntry("ACC", "0x11", "R", "dbg_acc", "Accumulator debug readback."),
    RegisterEntry("PC", "0x12", "R", "dbg_pc", "Program counter debug readback in bits `[3:0]`."),
    RegisterEntry("DMEM", "0x20-0x2F", "R", "dbg_mem_data", "Data-memory debug readback selected by address bits `[3:0]`."),
    RegisterEntry("CONTROL", "0x30", "RW", "state", "Write bit 0 starts/re-holds execution; read bits `[1:0]` are `LOAD`, `RUN`."),
    RegisterEntry("UNMAPPED", "other", "R", "zero", "Unmapped reads return zero; unmapped writes are ignored."),
)

PROTOCOLS: tuple[ProtocolView, ...] = (
    ProtocolView("MMIO", "rtl/simple_cpu_mmio.sv", "tb/mmio_bus.py", "bus_addr", "Always-ready native bus."),
    ProtocolView("MMIO wait", "rtl/simple_cpu_mmio_wait.sv", "tb/mmio_bus.py", "bus_addr", "Same map with delayed `bus_ready`."),
    ProtocolView("APB", "rtl/simple_cpu_apb.sv", "tb/apb_bus.py", "paddr", "APB setup/access wrapper forwards `PADDR`."),
    ProtocolView("Wishbone", "rtl/simple_cpu_wishbone.sv", "tb/wishbone_bus.py", "wb_adr_i", "Wishbone wrapper forwards `wb_adr_i`."),
    ProtocolView("AXI-Lite", "rtl/simple_cpu_axi_lite.sv", "tb/axi_lite_bus.py", "axi_awaddr/axi_araddr", "AXI-Lite wrapper forwards accepted write/read addresses."),
)

EXPECTED_CONSTANTS = {
    "ADDR_STATUS": 0x10,
    "ADDR_ACC": 0x11,
    "ADDR_PC": 0x12,
    "ADDR_CONTROL": 0x30,
}


def _sv_int(value: str) -> int:
    value = value.strip()
    if "'h" in value.lower():
        return int(value.split("'h", 1)[1], 16)
    if "'d" in value.lower():
        return int(value.split("'d", 1)[1], 10)
    return int(value, 0)


def parse_sv_address_constants() -> dict[str, int]:
    text = (PROJECT_ROOT / "rtl" / "simple_cpu_mmio.sv").read_text(encoding="utf-8")
    constants: dict[str, int] = {}
    for match in re.finditer(r"\blocalparam\s+logic\s+\[[^\]]+\]\s+(ADDR_[A-Z_]+)\s*=\s*([^;]+);", text):
        constants[match.group(1)] = _sv_int(match.group(2))
    return constants


def parse_python_address_constants() -> dict[str, int]:
    text = (PROJECT_ROOT / "tb" / "mmio_bus.py").read_text(encoding="utf-8")
    constants: dict[str, int] = {}
    for match in re.finditer(r"^(ADDR_[A-Z_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*$", text, re.M):
        constants[match.group(1)] = int(match.group(2), 0)
    return constants


def validate_register_map() -> list[str]:
    failures: list[str] = []
    sv_constants = parse_sv_address_constants()
    py_constants = parse_python_address_constants()

    for name, expected in EXPECTED_CONSTANTS.items():
        if sv_constants.get(name) != expected:
            failures.append(f"rtl/simple_cpu_mmio.sv `{name}` expected 0x{expected:02X}, got {sv_constants.get(name)}")
        if py_constants.get(name) != expected:
            failures.append(f"tb/mmio_bus.py `{name}` expected 0x{expected:02X}, got {py_constants.get(name)}")

    for path in ("tb/apb_bus.py", "tb/wishbone_bus.py", "tb/axi_lite_bus.py"):
        text = (PROJECT_ROOT / path).read_text(encoding="utf-8")
        for name in EXPECTED_CONSTANTS:
            if name not in text:
                failures.append(f"{path} does not import/use `{name}` from tb.mmio_bus")

    for protocol in PROTOCOLS:
        if not (PROJECT_ROOT / protocol.rtl).exists():
            failures.append(f"{protocol.name}: missing RTL file `{protocol.rtl}`")
        if not (PROJECT_ROOT / protocol.bus_helper).exists():
            failures.append(f"{protocol.name}: missing bus helper `{protocol.bus_helper}`")

    return failures


def render_markdown() -> str:
    failures = validate_register_map()
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise ValueError(f"register map is invalid:\n{joined}")

    lines = [
        "<!-- Generated by scripts/register_map.py. Do not edit by hand. -->",
        "",
        "# Wrapper Register Map",
        "",
        "This page is generated from the shared MMIO address contract and checked by the Python-model CI lane.",
        "",
        "## Summary",
        "",
        f"- Register regions: {len(REGISTERS)}",
        f"- Protocol views: {len(PROTOCOLS)}",
        "- Address constants are checked against `rtl/simple_cpu_mmio.sv` and `tb/mmio_bus.py`.",
        "- APB, Wishbone, and AXI-Lite Python BFMs are checked to reuse the shared MMIO constants.",
        "",
        "## Register Regions",
        "",
        "| Name | Address | Access | Producer | Description |",
        "|---|---|---|---|---|",
    ]

    for entry in REGISTERS:
        lines.append(
            f"| `{entry.name}` | `{entry.address}` | `{entry.access}` | `{entry.producer}` | {entry.description} |"
        )

    lines.extend(["", "## Protocol Views", "", "| Protocol | RTL | Bus helper | Address signal | Notes |", "|---|---|---|---|---|"])
    for protocol in PROTOCOLS:
        lines.append(
            f"| {protocol.name} | `{protocol.rtl}` | `{protocol.bus_helper}` | `{protocol.address_signal}` | {protocol.notes} |"
        )

    lines.extend(
        [
            "",
            "Regenerate this page after intentional register-map edits with:",
            "",
            "```powershell",
            ".\\scripts\\generate-register-map.ps1",
            "```",
            "",
            "```bash",
            "bash scripts/generate-register-map.sh",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and check the wrapper register map catalog.")
    parser.add_argument("--output", type=Path, default=Path("docs/register-map.md"))
    parser.add_argument("--check", action="store_true", help="Fail if the generated output is stale.")
    args = parser.parse_args()

    output_path = (PROJECT_ROOT / args.output).resolve()
    expected = render_markdown()

    if args.check:
        if not output_path.exists():
            print(f"Register map catalog is missing: {output_path}", file=sys.stderr)
            raise SystemExit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"Register map catalog is stale: {output_path}. "
                "Regenerate with scripts/generate-register-map.*",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"Register map catalog is up to date: {args.output}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
