from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = PROJECT_ROOT / "scripts"
WINDOWS_DIR = SCRIPTS_DIR / "windows"
LINUX_DIR = SCRIPTS_DIR / "linux"

SPECIAL_ENTRYPOINTS = {
    "install-tools": {
        "windows": "scripts/windows/install-tools.ps1",
        "linux": "scripts/linux/install-tools-ubuntu.sh",
        "top_windows": "scripts/install-tools.ps1",
        "top_linux": "scripts/install-tools-ubuntu.sh",
        "note": "Installer names differ by platform because the Linux implementation is Ubuntu-specific.",
    },
    "open-waves": {
        "windows": "scripts/windows/open-waves.ps1",
        "linux": "scripts/linux/open-waves.sh",
        "top_windows": "scripts/open-waves.ps1",
        "top_linux": "scripts/open-waves.sh",
        "note": "Also has `scripts/open-waves.cmd` and `scripts/windows/open-waves.cmd` convenience launchers.",
    },
}


@dataclass(frozen=True)
class ScriptEntrypoint:
    name: str
    top_windows: str
    top_linux: str
    windows_impl: str
    linux_impl: str
    note: str = ""


def script_rel(path: Path) -> str:
    return path.relative_to(PROJECT_ROOT).as_posix()


def paired_names() -> tuple[str, ...]:
    top_ps1 = {path.stem for path in SCRIPTS_DIR.glob("*.ps1")}
    top_sh = {path.stem for path in SCRIPTS_DIR.glob("*.sh")}
    names = (top_ps1 & top_sh) - set(SPECIAL_ENTRYPOINTS)
    return tuple(sorted(names))


def script_entrypoints() -> tuple[ScriptEntrypoint, ...]:
    entries = [
        ScriptEntrypoint(
            name=name,
            top_windows=f"scripts/{name}.ps1",
            top_linux=f"scripts/{name}.sh",
            windows_impl=f"scripts/windows/{name}.ps1",
            linux_impl=f"scripts/linux/{name}.sh",
        )
        for name in paired_names()
    ]

    for name, fields in SPECIAL_ENTRYPOINTS.items():
        entries.append(
            ScriptEntrypoint(
                name=name,
                top_windows=fields["top_windows"],
                top_linux=fields["top_linux"],
                windows_impl=fields["windows"],
                linux_impl=fields["linux"],
                note=fields["note"],
            )
        )

    return tuple(sorted(entries, key=lambda entry: entry.name))


def readme_common_entrypoints() -> set[str]:
    text = (SCRIPTS_DIR / "README.md").read_text(encoding="utf-8")
    match = re.search(r"Common entrypoints:\n\n(?P<body>.*?)(?:\n\nWhen adding a new automation flow:)", text, re.S)
    if not match:
        return set()
    return set(re.findall(r"`([^`]+)`\s+\(`", match.group("body")))


def validate_script_entrypoints() -> list[str]:
    failures: list[str] = []
    entries = script_entrypoints()
    names = [entry.name for entry in entries]
    if len(names) != len(set(names)):
        failures.append("script catalog: duplicate entrypoint names found")

    for entry in entries:
        for label, rel in (
            ("top-level PowerShell wrapper", entry.top_windows),
            ("top-level bash wrapper", entry.top_linux),
            ("Windows implementation", entry.windows_impl),
            ("Linux implementation", entry.linux_impl),
        ):
            if not (PROJECT_ROOT / rel).exists():
                failures.append(f"{entry.name}: missing {label}: {rel}")

    readme_names = readme_common_entrypoints()
    expected_readme_names = {entry.name for entry in entries}
    # The platform-specific installer is documented as `install-tools` in this generated catalog.
    expected_readme_names.discard("install-tools")
    for missing in sorted(expected_readme_names - readme_names):
        failures.append(f"scripts/README.md common entrypoints missing `{missing}`")
    for extra in sorted(readme_names - expected_readme_names):
        # Keep this as a warning-level validation failure so the generated catalog and README stay aligned.
        if extra != "install-tools":
            failures.append(f"scripts/README.md common entrypoints lists unknown `{extra}`")

    return failures


def render_markdown() -> str:
    failures = validate_script_entrypoints()
    if failures:
        joined = "\n".join(f"- {failure}" for failure in failures)
        raise ValueError(f"script catalog is invalid:\n{joined}")

    entries = script_entrypoints()
    lines = [
        "<!-- Generated by scripts/script_catalog.py. Do not edit by hand. -->",
        "",
        "# Script Catalog",
        "",
        "This page is generated from the cross-platform wrapper layout under `scripts/` and checked by the Python-model CI lane.",
        "",
        "## Summary",
        "",
        f"- Cross-platform entrypoints: {len(entries)}",
        "- Platform implementations: `scripts/windows/*` and `scripts/linux/*`",
        "- Compatibility wrappers: top-level `scripts/*.ps1` and `scripts/*.sh`",
        "",
        "## Entrypoints",
        "",
        "| Entrypoint | PowerShell wrapper | Bash wrapper | Windows implementation | Linux implementation | Note |",
        "|---|---|---|---|---|---|",
    ]

    for entry in entries:
        lines.append(
            "| `{name}` | `{top_windows}` | `{top_linux}` | `{windows_impl}` | `{linux_impl}` | {note} |".format(
                name=entry.name,
                top_windows=entry.top_windows,
                top_linux=entry.top_linux,
                windows_impl=entry.windows_impl,
                linux_impl=entry.linux_impl,
                note=entry.note or "",
            )
        )

    lines.extend(
        [
            "",
            "Regenerate this page after intentional script-layout edits with:",
            "",
            "```powershell",
            ".\\scripts\\generate-script-catalog.ps1",
            "```",
            "",
            "```bash",
            "bash scripts/generate-script-catalog.sh",
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate and check the cross-platform script catalog.")
    parser.add_argument("--output", type=Path, default=Path("docs/script-catalog.md"))
    parser.add_argument("--check", action="store_true", help="Fail if the generated output is stale.")
    args = parser.parse_args()

    output_path = (PROJECT_ROOT / args.output).resolve()
    expected = render_markdown()

    if args.check:
        if not output_path.exists():
            print(f"Script catalog is missing: {output_path}", file=sys.stderr)
            raise SystemExit(1)
        actual = output_path.read_text(encoding="utf-8")
        if actual != expected:
            print(
                f"Script catalog is stale: {output_path}. "
                "Regenerate with scripts/generate-script-catalog.*",
                file=sys.stderr,
            )
            raise SystemExit(1)
        print(f"Script catalog is up to date: {args.output}")
        return

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(expected, encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
